# Configuration for Alacritty, the GPU enhanced terminal emulator.
# Carl Lundin
import:
  - ~/.config/alacritty/dracula.yml

window:
  padding:
    x: 16
    y: 16
  # Uncomment on MacOS
  # decorations: borderless
  decorations: full
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true
  history: 10000
  opacity: 0.9
font:
  normal:
    # Uncomment if Hacker Nerd Font Mono installed
    family: FiraCode Nerd Font
    style: Regular
  size: 12.0
selection:
  save_to_clipboard: true
live_config_reload: true
